# Generated by Django 2.2 on 2019-08-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, verbose_name='用户id')),
                ('content', models.TextField(verbose_name='内容')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='用户id')),
                ('contact', models.CharField(max_length=50, null=True, verbose_name='用户id')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], default='active', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(null=True, verbose_name='回复')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='对应 scrapy 的 name 代号（不对外显示）')),
                ('author', models.CharField(max_length=100, verbose_name='来源站点的作者名')),
                ('cname', models.CharField(max_length=100, verbose_name='来源站点的名称')),
                ('link', models.CharField(max_length=200, verbose_name='来源站点的主页')),
                ('favicon', models.CharField(default='', max_length=100, verbose_name='来源站点的图标')),
                ('brief', models.CharField(max_length=200, verbose_name='简介')),
                ('star', models.IntegerField(default=20, verbose_name='评级，10，20，30')),
                ('freq', models.CharField(choices=[('日更', '每天更新'), ('周更', '每周更新'), ('月更', '每月更新')], max_length=20, verbose_name='更新频率')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], default='active', max_length=20, verbose_name='状态，默认 active 激活，close 关闭')),
                ('copyright', models.IntegerField(choices=[(0, '未知'), (10, '不可转载'), (20, '仅可转载摘要'), (30, '可以全文转载')], default=0, null=True, verbose_name='版权')),
                ('tag', models.CharField(choices=[('前端', '前端'), ('客户端', '客户端'), ('后端', '后端'), ('全栈', '全栈'), ('产品', '产品'), ('安全', '安全'), ('设计', '设计'), ('测试', '测试'), ('刊物', '刊物'), ('算法', '算法'), ('大数据', '大数据')], max_length=20, null=True, verbose_name='所属领域，一个词形容')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='标题')),
                ('uindex', models.IntegerField(db_index=True, unique=True, verbose_name='一个时间戳表示的唯一地址')),
                ('content', models.TextField(verbose_name='内容')),
                ('src_url', models.CharField(max_length=500, verbose_name='原始链接')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], default='active', max_length=20, verbose_name='状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(default='', null=True, verbose_name='备注')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Site')),
            ],
        ),
    ]
