# Generated by Django 2.2 on 2019-09-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20190828_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(max_length=50, null=True, verbose_name='用户联系方式'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tag',
            field=models.CharField(choices=[('前端', '前端'), ('客户端', '客户端'), ('后端', '后端'), ('全栈', '全栈'), ('产品', '产品'), ('营销', '营销'), ('安全', '安全'), ('设计', '设计'), ('测试', '测试'), ('运维', '运维'), ('刊物', '刊物'), ('算法', '算法'), ('大数据', '大数据')], max_length=20, null=True, verbose_name='一个词形容'),
        ),
    ]
