# Generated by Django 2.2 on 2019-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190906_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='site',
            name='creator',
            field=models.CharField(blank=True, choices=[('system', '系统录入'), ('user', '用户提交')], default='system', max_length=20, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='article',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户联系方式'),
        ),
        migrations.AlterField(
            model_name='message',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='message',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='site',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='site',
            name='copyright',
            field=models.IntegerField(blank=True, choices=[(0, '未知'), (10, '不可转载'), (20, '仅可转载摘要'), (30, '可以全文转载')], default=0, null=True, verbose_name='版权'),
        ),
        migrations.AlterField(
            model_name='site',
            name='favicon',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='site',
            name='freq',
            field=models.CharField(choices=[('小时', '每小时更新'), ('日更', '每天更新'), ('周更', '每周更新'), ('月更', '每月更新')], max_length=20, verbose_name='更新频率'),
        ),
        migrations.AlterField(
            model_name='site',
            name='remark',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tag',
            field=models.CharField(blank=True, choices=[('前端', '前端'), ('客户端', '客户端'), ('后端', '后端'), ('全栈', '全栈'), ('产品', '产品'), ('营销', '营销'), ('安全', '安全'), ('设计', '设计'), ('测试', '测试'), ('运维', '运维'), ('刊物', '刊物'), ('算法', '算法'), ('大数据', '大数据'), ('RSS', 'RSS')], max_length=20, null=True, verbose_name='一个词形容'),
        ),
    ]
