# Generated by Django 2.2.4 on 2019-09-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190829_0104'),
        ('web', '0004_auto_20190906_1605'),
    ]

    operations = [
    ]
