# Generated by Django 2.2.4 on 2019-09-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190911_2141'),
        ('web', '0006_auto_20190906_1618'),
    ]

    operations = [
    ]
