# Generated by Django 2.2.4 on 2019-09-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_merge_20190913_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='rss',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='RSS地址'),
        ),
    ]
