# Generated by Django 2.2.4 on 2019-10-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_site_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='star',
            field=models.IntegerField(default=20, verbose_name='评级，1-39'),
        ),
    ]
