# Generated by Django 2.2.4 on 2019-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20191022_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='cname',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='site',
            name='link',
            field=models.CharField(max_length=200, verbose_name='主页'),
        ),
        migrations.AlterField(
            model_name='site',
            name='star',
            field=models.IntegerField(default=20, verbose_name='评级'),
        ),
    ]
