# Generated by Django 2.2.4 on 2019-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20191104_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
    ]
