# Generated by Django 2.2.4 on 2019-11-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20191120_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
