# Generated by Django 2.2.9 on 2020-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20191121_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_id', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='平台+id')),
                ('oauth_name', models.CharField(max_length=100, verbose_name='昵称')),
                ('oauth_avatar', models.CharField(max_length=200, verbose_name='头像')),
                ('oauth_email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('oauth_blog', models.CharField(blank=True, max_length=200, null=True, verbose_name='blog')),
                ('oauth_ext', models.TextField(blank=True, default='', null=True, verbose_name='完整信息')),
                ('avatar', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='头像')),
                ('status', models.CharField(choices=[('active', '激活'), ('close', '关闭，下线')], default='active', max_length=20, verbose_name='状态')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.AlterField(
            model_name='site',
            name='star',
            field=models.IntegerField(db_index=True, default=20, verbose_name='评级'),
        ),
    ]
