# Generated by Django 2.2.7 on 2020-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20200115_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_recent',
            field=models.BooleanField(choices=[(True, '最近文章'), (False, '历史文章')], db_index=True, default=True, verbose_name='最近的文章'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
