# Generated by Django 2.2.7 on 2020-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='src_url',
            field=models.CharField(max_length=1024, verbose_name='原始链接'),
        ),
    ]
