# Generated by Django 2.2.7 on 2020-04-11 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20200411_0332'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('src_url', 'site')},
        ),
    ]
