# Generated by Django 2.2.7 on 2020-05-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20200411_1945'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('src_url', 'site'), ('src_url', 'site', 'title')},
        ),
    ]
