# Generated by Django 2.2.7 on 2020-05-04 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_auto_20200502_1053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('src_url', 'site'), ('title', 'site')},
        ),
    ]
