# Generated by Django 2.2.7 on 2020-05-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_auto_20200504_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uindex', models.IntegerField(unique=True, verbose_name='唯一地址')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='作者')),
                ('src_url', models.CharField(max_length=1024, verbose_name='原始链接')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.User')),
            ],
        ),
    ]
