# Generated by Django 2.2.7 on 2020-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_userarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='author',
            field=models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='作者'),
        ),
    ]
