# Generated by Django 2.2.7 on 2020-06-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_auto_20200621_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(db_index=True, verbose_name='站点')),
                ('site_cname', models.CharField(max_length=100, verbose_name='名称')),
                ('site_author', models.CharField(blank=True, default='None', max_length=100, null=True, verbose_name='作者')),
                ('site_favicon', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='favicon')),
                ('site_star', models.IntegerField(default=20, verbose_name='评级')),
                ('update_count', models.IntegerField(default=0, verbose_name='更新数')),
                ('update_ids', models.TextField(default='[]', verbose_name='更新索引')),
                ('update_time', models.DateTimeField(verbose_name='最后更新时间')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='freq',
        ),
        migrations.RemoveField(
            model_name='site',
            name='tag',
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='scrapy代号'),
        ),
    ]
