# Generated by Django 2.2.7 on 2020-06-30 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_auto_20200626_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteUpdate',
        ),
    ]
