# Generated by Django 2.2.7 on 2020-07-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_delete_siteupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='author',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='作者'),
        ),
    ]
