# Generated by Django 2.2.7 on 2020-07-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_auto_20200705_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, '默认'), (10, '初级捐赠'), (20, '高级捐赠')], default=1, null=True, verbose_name='等级'),
        ),
    ]
