# Generated by Django 2.2.7 on 2020-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarticle',
            name='uindex',
            field=models.IntegerField(verbose_name='地址'),
        ),
    ]
