# Generated by Django 3.1 on 2020-08-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_auto_20200805_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1024, verbose_name='原始链接')),
                ('action', models.IntegerField(choices=[(10, 'RSS 源'), (11, 'ershicimi 爬虫文章列表'), (12, 'wemp 爬虫文章列表'), (13, 'chuansongme 爬虫文章列表'), (20, 'mpwx 文章详情'), (21, 'ershicimi 爬虫文章详情'), (22, 'wemp 爬虫文章详情'), (23, 'chuansongme 爬虫文章详情')], verbose_name='链接类型')),
                ('rsp', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
                ('status', models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '处理成功'), (3, '超时'), (4, '解析异常'), (5, '交还次数超限')], db_index=True, default=0, verbose_name='状态')),
                ('dvc_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='设备号')),
                ('dvc_type', models.CharField(blank=True, choices=[('user', '用户'), ('robot', '机器人')], max_length=16, null=True, verbose_name='设备身份')),
                ('dvc_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='设备IP')),
                ('dvc_ext', models.TextField(blank=True, default='', null=True, verbose_name='设备额外信息')),
                ('giveback', models.IntegerField(default=0, verbose_name='交还次数')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.TextField(blank=True, default='', null=True, verbose_name='备注')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.site')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.user')),
            ],
        ),
    ]
