# Generated by Django 3.1 on 2020-08-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.IntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '处理成功'), (3, '超时'), (4, '解析异常'), (5, '交还次数超限'), (6, '被发布者删除')], db_index=True, default=0, verbose_name='状态'),
        ),
    ]
