# Generated by Django 3.1 on 2020-08-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_auto_20200819_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='action',
            field=models.IntegerField(choices=[(10, 'RSS 源'), (11, 'ershicimi 文章列表'), (12, 'wemp 文章列表'), (13, 'chuansongme 文章列表'), (14, 'any 文章列表'), (20, 'mpwx 文章详情'), (21, 'ershicimi 文章详情'), (22, 'wemp 文章详情'), (23, 'chuansongme 文章详情'), (24, 'any 文章详情')], verbose_name='链接类型'),
        ),
    ]
