# Generated by Django 3.1 on 2020-08-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_auto_20200821_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
