# Generated by Django 3.1 on 2020-08-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_auto_20200823_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='creator',
            field=models.CharField(blank=True, choices=[('system', '系统录入'), ('user', 'RSS'), ('podcast', '播客'), ('wemp', '公众号')], db_index=True, default='system', max_length=20, null=True, verbose_name='创建人'),
        ),
    ]
