# Generated by Django 3.1.3 on 2022-04-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_auto_20200830_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
