# Generated by Django 3.1.3 on 2022-04-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_delete_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserArticle',
        ),
    ]
